server:
  port: 8004

spring:

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: YEKDB
    password: YEK,123456
    url: jdbc:mysql://192.168.80.174:3306/XLSTOHDDB?useUnicode=true&characterEncoding=utf-8

  jpa:
    show-sql: true

  thymeleaf:
      cache: false
      mode: LEGACYHTML5



##  username: YEKDB
##  password: YEK,123456
##  url: jdbc:mysql://192.168.80.174:3306/XLSTOHDDB?useUnicode=true&characterEncoding=utf-8
